# Generated by Django 2.0.2 on 2019-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cereal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fat', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('fiber', models.FloatField()),
                ('carbo', models.FloatField()),
                ('sugars', models.IntegerField()),
                ('potass', models.IntegerField()),
                ('vitamins', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
