# Generated by Django 2.0.2 on 2019-12-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereals', '0003_auto_20191203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cereal',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
